#!/bin/bash

GIT=`which git`

readarray -t backups < backup-files.txt;

for file in $"${backups[@]}"
do
    file=$(realpath "$file")
    new_name=./backup-files/$(echo "$file" | tr / .)

    if [[ -z "${file}" || "$file" =~ ^# ]]; then
	continue
    fi
    
    echo newname: "$new_name"
    mkdir -p ./backup-files && cp "$file" "$new_name"
done

echo =========================================================================

${GIT} add --all .
${GIT} commit -m "backup at `date "+%Y-%m-%d %H:%M:%S"`"
${GIT} push
