#!/bin/bash

GIT=`which git`

readarray -t backups < backup-files.txt;

for line in $"${backups[@]}"
do

    if [[ -z "${line}" || "$line" =~ ^# ]]; then
	continue
    fi
    
    file=$(echo $line | sed "s|~|$HOME|" )
    new_name=./backup-files/$(echo "$file" | tr / @)
    
    echo newname: "$new_name"
    mkdir -p ./backup-files && cp "$file" "$new_name"
done

echo =========================================================================

${GIT} add --all .
${GIT} commit -m "backup at `date "+%Y-%m-%d %H:%M:%S"`"
${GIT} push
